// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxo1TQH6X15gtITX-A2TQoTqVcr6L9Rc',
    appId: '1:528039122062:android:1190c92d5f0e9ebbdaa5df',
    messagingSenderId: '528039122062',
    projectId: 'exa-spacex',
    databaseURL: 'https://exa-spacex-default-rtdb.firebaseio.com',
    storageBucket: 'exa-spacex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIH9k1Q7Jh6jrDiLBxwH7-8b831YoB6YQ',
    appId: '1:528039122062:ios:92843f1b8fc11f21daa5df',
    messagingSenderId: '528039122062',
    projectId: 'exa-spacex',
    databaseURL: 'https://exa-spacex-default-rtdb.firebaseio.com',
    storageBucket: 'exa-spacex.appspot.com',
    androidClientId: '528039122062-96b4ds3aktmtldajfnot0tng3cap025u.apps.googleusercontent.com',
    iosClientId: '528039122062-qjpcfks0h5firacaecuol3qdqlgnd3hi.apps.googleusercontent.com',
    iosBundleId: 'com.exapps.stormx',
  );

}